// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'This platform is not supported for Firebase configuration.',
        );
    }
  }

  ///  Android
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'wedNfr4rZCr4IkpEede+5gSPN76RC5pchp9sDl3epZaNyvUlSt7cXY+/puYhJoiGgcp50WuqNCVtlf8i6A/LdA==',
    appId: '1:782945913757:android:ef57d25838bb4532e37d74',
    messagingSenderId: '782945913757',
    projectId: 'hrr-erp-2',
  );

  ///  iOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATMi_WzfUnBfhb66_FR8c1Fg_zEwHyaCs',
    appId: '1:782945913757:ios:7a99b21610350f2be37d74',
    messagingSenderId: '782945913757',
    projectId: 'hrr-erp-2',
    iosBundleId: 'com.k3htechnologies.hrr.erp',
  );
}